<a href="https://colab.research.google.com/github/Raj3000end/Pytorch/blob/main/Py_torch_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
float_32_tensor = torch.tensor([3.0,4.0,5],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

####"what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where"

In [6]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Shape of tensor : {some_tensor.shape} ")
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Device on tensor is stored : {some_tensor.device}")

tensor([[0.9671, 0.0070, 0.7794, 0.1796],
        [0.2146, 0.5514, 0.7109, 0.4617],
        [0.9377, 0.6550, 0.9472, 0.8909]])
Shape of tensor : torch.Size([3, 4]) 
Datatype of tensor : torch.float32
Device on tensor is stored : cpu


###Tensor Operations

In [7]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [8]:
tensor * 10

tensor([10, 20, 30])

In [9]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [10]:
tensor = tensor + 10
tensor


tensor([1, 2, 3])

In [11]:
torch.multiply(tensor, 10)


tensor([10, 20, 30])

In [13]:
print(tensor, "*" ,tensor)
print("Equals : ", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals :  tensor([1, 4, 9])
