<a href="https://colab.research.google.com/github/Raj3000end/Pytorch/blob/main/Py_torch_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.1.0+cu118'

In [ ]:
scalar = torch.tensor(7)
scalar
#scalar.ndim - ouput 0


7

In [ ]:
scalar.item()

14

In [ ]:
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector.ndim

1

In [ ]:
vector2 = torch.tensor([[2,3,5]])
vector2

tensor([[2, 3, 5]])

In [ ]:
vector2.ndim

2

In [ ]:
vector.shape



torch.Size([2])

In [ ]:
vector2.shape

torch.Size([1, 3])

In [ ]:
vector3 = torch.tensor([[[1,2,3,4,5]]])
vector3.shape

torch.Size([1, 1, 5])

In [ ]:
vector3.ndim


2

In [ ]:
vector4 = torch.tensor([[[1,2,3,4,5],[1,2,3,4,6],[1,2,3,4,5],[1,2,3,4,6]]])
vector4.shape

torch.Size([1, 4, 5])

In [ ]:
matrix = torch.tensor([[[[2,3,5],
                      [1,2,8]]]])
matrix

tensor([[[[2, 3, 5],
          [1, 2, 8]]]])

In [ ]:
matrix.ndim


4

In [ ]:
matrix.shape

torch.Size([1, 1, 2, 3])

In [ ]:
random_tensor = torch.rand(size = (224,224,3))
random_tensor, random_tensor.dtype

(tensor([[[0.2070, 0.9154, 0.2701],
          [0.5116, 0.7140, 0.5529],
          [0.0899, 0.2235, 0.7803],
          ...,
          [0.9610, 0.2014, 0.0551],
          [0.7362, 0.8527, 0.2270],
          [0.0869, 0.4029, 0.4594]],
 
         [[0.4451, 0.3106, 0.4354],
          [0.9179, 0.5722, 0.8878],
          [0.1057, 0.3530, 0.4488],
          ...,
          [0.1847, 0.6487, 0.7145],
          [0.2586, 0.4385, 0.4844],
          [0.0875, 0.4159, 0.7268]],
 
         [[0.7709, 0.6136, 0.3910],
          [0.8874, 0.5373, 0.5464],
          [0.2965, 0.1714, 0.3197],
          ...,
          [0.9778, 0.8907, 0.3966],
          [0.7958, 0.3792, 0.4089],
          [0.7495, 0.2572, 0.6672]],
 
         ...,
 
         [[0.1046, 0.2591, 0.9045],
          [0.2222, 0.7291, 0.4393],
          [0.6927, 0.2000, 0.3305],
          ...,
          [0.8064, 0.2175, 0.6396],
          [0.2905, 0.8211, 0.9043],
          [0.4732, 0.1563, 0.5777]],
 
         [[0.0387, 0.7269, 0.1935],
          [0

In [ ]:
random_tensor.shape, random_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
rand_ten = torch.rand(size = (3,4))
rand_ten.shape, rand_ten.dtype

(torch.Size([3, 4]), torch.float32)

In [ ]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
zeros_new = torch.zeros(size = (3,4))
zeros_new.shape, zeros_new.ndim, zeros_new.dtype

(torch.Size([3, 4]), 2, torch.float32)

In [ ]:
new_range = torch.arange(start = 0, end = 10, step = 1)
new_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros = torch.zeros_like(input = new_range)
ten_ones = torch.ones_like(input = new_range)
print(ten_zeros)
ten_ones

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
git remote add origin https://github.com/Raj3000end/Pytorch.git
git branch -M main
git push -u origin main

SyntaxError: ignored